### ISSUE TITLE
JF 10.7.0 update broke this plugin.

### ISSUE THREAD

**Issue by DougS2K** [jellyfin/jellyfin-plugin-playbackreporting#34] opened 2021-03-13 20:59 UTC
Seems the recent JF update has broke some of this plugin. The playback tab no longer lists the playback history at the bottom and users are reported playing back tens of thousands of media a day.
Example:
![image](https://user-images.githubusercontent.com/638706/111051195-88f66a80-8451-11eb-9157-56b78942d3f2.png)

**Comment by juligreen** [comment] 2021-03-13 21:00
I have the same issue: 
![image](https://user-images.githubusercontent.com/25890405/111044223-8db62100-8447-11eb-8951-7d6eaf39b4d8.png)

**Comment by oddstr13** [comment] 2021-03-13 22:15
Looks like this is a duplicate of #32

**Closed by oddstr13** 2021-03-13 22:15 UTC
