### ISSUE TITLE
Playtime is off the charts, literally. More than 24h in one day per user

### ISSUE THREAD

**Issue by skiwlkr** [jellyfin/jellyfin-plugin-playbackreporting#69] opened 2022-12-13 10:12 UTC
I can't figure out why this happens, but some users have an extreme amount of playtime. More than 24h per day, which obviously can't be right. Why could this happen?
JF Version: 10.8.4
Playback Reporting 13.0.0.0

![image](https://user-images.githubusercontent.com/41541087/207289595-7fc802d1-fcad-4408-bee1-4c6f8daea6ce.png)

**Comment by Slug-Cat** [comment] 2023-03-27 21:10
I have also observed this, not sure what causes it.

**Comment by BenStokmans** [comment] 2023-04-03 19:27
I also observed this, for me its seems to be caused by users (mostly on mobile in my experience) closing down their device and then sometimes hours later picking it back up reconnecting the app to the server an registering all the time that has passed as watch time.

**Comment by GeoffreyCoulaud** [comment] 2023-04-05 13:52
I can attest this happens to me too. However, it's not only mobile users. It happens in `Jellyfin Media Player`, not only `Jellyfin Android`.

**Comment by sebastienPoussard** [comment] 2023-04-06 16:14
same problem.

**Comment by LelouBil** [comment] 2023-08-18 17:38
same issue

**Closed** 2024-07-17 17:05 UTC
